export const language = {
  en:{ 
    tmsConnectionFailed:'Failed to connect TMS server',
    counterSignin:'Signed in to the counter successfully',
    confirmMessage:'Are you sure want to delete?',
    logoutMessage : 'Are you sure want to logout?',
    unableDelete : 'Unable to delete',
    unableSubmit : 'Unable to submit',
    deleteMsg : 'deleted successfully',
    invalidExcel : 'Invalid excel file',
    processFirst : 'Please select unit first', 
    process : 'Please select process',
    userRole : 'Please select user role',
    selectFingerindex : 'Please select finger index and try again',
    unableConnect : 'Unable to connect secugen device',
    minFinger: 'Kindly upload minimum three fingerprints',
    captureCode : 'Fingerprint capture error code: ',
    description : '.\nDescription:  ',
    matchFinger : 'Fingerprint details are matched successfully',
    incorrectFinger : 'Incorrect fingerprint details',
    matchingFailed : 'Failed to match the template',
    codeVerify : 'Your code has successfully verified',
    codeSent : 'The verification code has been sent to your registered email address',
    codeErr : 'Error in sending code',
    contactAdmin : 'Please contact your administrator',
    confirmMessage1:'Your session is about to expire.Do you need more time?',
    unableConnectSign : 'Unable to connect device',
    getSign : 'Please get the signature from the applicant',
    SelectDoc:'Select document type for document #',
    SelectDocName:'Enter document name for document #',
  },
  ta:{
    confirmMessage:'இதை நிச்சயமாக நீக்க விரும்புகிறீர்களா?'
  }
};